const styles = {
  PinCard: {
    backgroundColor: "rgba(0, 0, 0, 1)",
    color: "white",
    borderRadius: "10px",
    height: "100px",

    width: "95vw",
    float: "right",
    zIndex: 2,
    pointerEvents: "none",
    position: "absolute",
    // right: 0,
    margin: "80px 10px",
    transition: "opacity 1.5s",
    display: "flex",
  },
  PinCardImg: {
    width: "100%",
    height: "100px",
    objectFit: "cover",
    borderRadius: "10px 10px 10px 10px",
  },
  PinCardTitleMain: {
    margin: "10px",
  },
  PinCardTitle: {
    fontFamily: "Roboto",
    fontSize: "0.8rem",
    fontWeight: "bold",
  },
  PinCardDescription: {
    fontFamily: "Roboto",
    fontSize: "10px",
    mt: "5px",
    fontWeight: 500,
    textOverflow: "ellipsis",
  },
  ActivePinCardMain: {
    backgroundColor: "rgba(0, 0, 0, 1)",
    color: "white",
    borderRadius: "10px",
    paddingBottom: "10px",
    width: "15rem",
    float: "right",
    transition: "opacity 1.5s",
    zIndex: 2,
    pointerEvents: "none",
    position: "absolute",
    right: 0,
    margin: "15px",
  },
  ActivePinCardImg: {
    width: "100%",
    height: "140px",
    objectFit: "cover",
    borderRadius: "10px 10px 0px 0px",
  },
  ActivePinHouseMain: {
    backgroundColor: "rgba(0, 0, 0, 1)",
    color: "white",
    borderRadius: "10px",
    zIndex: 2,
    padding: "10px",
    width: "fit-content",
    float: "right",
    pointerEvents: "none",
    position: "absolute",
    right: 0,
    transition: "opacity 0.5s",
    display: "flex",
    margin: "15px",
  },
  ActivePinHouseImg: {
    width: "120px",
    height: "100px",
    objectFit: "cover",
  },
  PinHouseCardDescription: {
    fontFamily: "Roboto",
    fontSize: "0.7rem",
    mt: "2px",
    fontWeight: "bold",
    textOverflow: "ellipsis",
  },
  PinHouseCardDescriptionSub: {
    fontFamily: "Roboto",
    fontSize: "0.6rem",
    mt: "3px",
    fontWeight: "bold",
    textOverflow: "ellipsis",
    color: "grey",
  },
  HousePinCardTitlemain: {
    margin: "0px 10px 10px 10px",
  },
  FilterTabsMain: {
    position: "fixed",
    top: "auto",
    bottom: "80px",
    width: "99%",
    "& .Mui-selected": {
      color: "black !important",
      backgroundColor: "white",
    },
  },
  AllTab: {
    display: "flex",
    justifyContent: "center",
    gap: "20px",
  },
  ResidentialCommercialTab: {
    display: "flex",
    justifyContent: "center",
    gap: "6px",
  },
  CompassText: {
    fontSize: { lg: "13px", md: "13px", sm: "13px", xs: "7px" },
    color: "white",
    fontWeight: "Segoeui",
  },
  CompassTextMain: {
    zIndex: 5,
    position: "absolute",
    bottom: { lg: 15, md: 15, sm: 15, xs: 20 },
    left: { lg: 70, md: 70, sm: 60, xs: 50 },
    userSelect: "none",
    pointerEvents: "none",
    WebkitUserDrag: "none",
    WebkitTouchCallout: "none",
    MozUserSelect: "none",
    bgColor: "red",
  },
  TabsMain: {
    width: "35%",
    marginTop: "7px",
    "& .MuiTabs-indicator": {
      backgroundColor: "#e11b22",
      color: "white",
      height: "3px",
    },
  },
  SideBarBtns: {
    visibility: "hidden",
    opacity: 0,
    position: "absolute",
    marginRight: "10px",
    right: "100%",
    transform: "translateX(-80%)",
    backgroundColor: "rgba(0,0,0,0.8)",
    color: "white",
    // padding: "5px 10px",
    padding: "3px 8px",
    borderRadius: "4px",
    fontSize: "11px",
    whiteSpace: "nowrap",
    zIndex: 1,
    transition: "visibility 0s, opacity 0.5s ease-out, transform 0.5s ease-out",
    animation: "none",
    textTransform: "capitalize",
  },
};

export default styles;
